name: Build tracker rules

on:
  schedule:                       # 每小时跑一次
    - cron:  '0 * * * *'          # GitHub cron 使用 UTC
  workflow_dispatch: {}           # 允许手动触发

# 允许工作流向仓库推送变更
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --disable-pip-version-check --no-cache-dir requests PyYAML

      - name: Prepare output directory
        run: mkdir -p dist

      - name: Generate rule file
        run: python src/main.py

      - name: Commit & push if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/trackers_list_rule.yaml"
          message: "auto: update tracker rules"
          default_author: github_actions
          push: true
